const specialProjects = [
  {
    title: "E-commerce Website Redesign",
    category: "Web Development",
    description: "Redesign an existing Shopify store with a modern, conversion-focused layout.",
    urgency: "Immediate",
    nda: true,
    budgetRange: "$800 - $1000",
    photos: ["https://res.cloudinary.com/dior4n7ve/image/upload/v1760263759/main-sample.png"],
    name: "Jessica Brown",
    role: "Business Owner",
    prefferredCommunication: "Email",
    contactTime: "Morning",
    createdBy: "2024-02-15T12:00:00Z", // Example ObjectId
    status: "Submitted",
  },
  {
    title: "Mobile App Prototype for Fitness Tracking",
    category: "UI/UX Design",
    description: "Create a clickable Figma prototype for a cross-platform fitness tracking app.",
    urgency: "1-2 weeks",
    nda: true,
    budgetRange: "$400 - $600",
    photos: ["https://res.cloudinary.com/dior4n7ve/image/upload/v1760263759/main-sample.png"],
    name: "Daniel Lee",
    role: "Startup Founder",
    prefferredCommunication: "Phone",
    contactTime: "Afternoon",
    createdBy: "2024-02-15T12:00:00Z",
    status: "Proposal_Sent",
  },
  {
    title: "Custom CRM Dashboard",
    category: "Software Development",
    description: "Develop a tailored CRM dashboard with analytics, task tracking, and user management.",
    urgency: "Immediate",
    nda: false,
    budgetRange: "$1500 - $2000",
    photos: ["https://res.cloudinary.com/dior4n7ve/image/upload/v1760263759/main-sample.png"],
    name: "Sophia Martinez",
    role: "Project Manager",
    prefferredCommunication: "In_app",
    contactTime: "Morning",
    createdBy: "2024-02-15T12:00:00Z",
    status: "In_Progress",
  },
  {
    title: "Corporate Branding Package",
    category: "Graphic Design",
    description: "Design a complete brand identity including logo, color palette, and marketing materials.",
    urgency: "Flexible",
    nda: true,
    budgetRange: "$300 - $500",
    photos: ["https://res.cloudinary.com/dior4n7ve/image/upload/v1760263759/main-sample.png"],
    name: "Michael Carter",
    role: "Marketing Director",
    prefferredCommunication: "Email",
    contactTime: "Evening",
    createdBy: "2024-02-15T12:00:00Z",
    status: "In_Review",
  },
  {
    title: "SEO Optimization for Travel Blog",
    category: "Digital Marketing",
    description: "Optimize on-page SEO, improve keyword targeting, and build high-quality backlinks.",
    urgency: "1-2 weeks",
    nda: false,
    budgetRange: "$250 - $400",
    photos: ["https://res.cloudinary.com/dior4n7ve/image/upload/v1760263759/main-sample.png"],
    name: "Emily Johnson",
    role: "Content Creator",
    prefferredCommunication: "In_app",
    contactTime: "Afternoon",
    createdBy: "652e91b2f7a5a23b4c7d8e95",
    status: "Delivered",
  },
];
